### ISSUE TITLE
problem with database.db despite successful processing of step 3 for kettle images

### ISSUE THREAD

**Issue by monajalal** [liuyuan-pal/NeRO#15]
I got this error at the step 7 of the custom data:
![Screenshot from 2023-06-20 14-20-32](https://github.com/liuyuan-pal/NeRO/assets/1892917/9cec89e1-f828-480c-a201-ea7ba01f6c21)

```
(nero) mona@ard-gpu-01:~/NeRO$ python run_training.py --cfg configs/custom/kettle_shape.yaml
train set len 99999999
Provide model format: '.bin' or '.txt'
Traceback (most recent call last):
  File "/home/mona/NeRO/run_training.py", line 10, in <module>
    Trainer(load_cfg(flags.cfg)).run()
  File "/home/mona/NeRO/train/trainer.py", line 100, in run
    self._init_dataset()
  File "/home/mona/NeRO/train/trainer.py", line 45, in _init_dataset
    val_set = name2dataset[val_type](val_cfg, False)
  File "/home/mona/NeRO/dataset/train_dataset.py", line 11, in __init__
    database = parse_database_name(self.cfg['database_name'])
  File "/home/mona/NeRO/dataset/database.py", line 409, in parse_database_name
    return name2database[database_type](database_name)
  File "/home/mona/NeRO/dataset/database.py", line 265, in __init__
    self._parse_colmap()
  File "/home/mona/NeRO/dataset/database.py", line 292, in _parse_colmap
    cameras, images, points3d = read_model(f'{self.root}/colmap/sparse/0')
TypeError: cannot unpack non-iterable NoneType object
```

Here's the structure I have:
```
(nero) mona@ard-gpu-01:~/NeRO/data$ tree -L 3 .
.
└── custom
    ├── kettle
    │   ├── database.db
    │   ├── database.db-shm
    │   ├── database.db-wal
    │   ├── dense
    │   ├── images
    │   ├── meta_info.txt
    │   ├── `.mlp
    │   ├── object_point_cloud.ply
    │   ├── points.ply
    │   ├── points.ply.vis
    │   └── sparse
    └── kettle.zip
```

why is the database empty if I have successfully run the `run_colmap` step you had in step 3 and was able to create the pointcloud of the kettle and its surrounding?

![Screenshot from 2023-06-20 14-22-29](https://github.com/liuyuan-pal/NeRO/assets/1892917/91292242-2828-4a02-913c-560bf94a291e)
Here's a test script for inspecting into the `database.db`:

```
import sqlite3

# Connect to the database
conn = sqlite3.connect('database.db')

# Create a cursor object
cursor = conn.cursor()

# Query the sqlite_master table to find the table name
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
table_names = cursor.fetchall()

# Print the table names
print(table_names)

# Retrieve the column names and first 5 rows of the first table in the list
if len(table_names) > 0:
    table_name = table_names[0][0]
    cursor.execute('SELECT * FROM {} LIMIT 0'.format(table_name))
    column_names = [description[0] for description in cursor.description]
    print(column_names)
    cursor.execute('SELECT * FROM {} LIMIT 5'.format(table_name))
    rows = cursor.fetchall()
    for row in rows:
        print(row)

# Close the cursor and the connection
cursor.close()
conn.close()
```

Here's the result I get from its execution:
```
(nero) mona@ard-gpu-01:~/NeRO/data/custom/kettle$ python test_db.py 
[('cameras',), ('sqlite_sequence',), ('images',), ('keypoints',), ('descriptors',), ('matches',), ('two_view_geometries',)]
['camera_id', 'model', 'width', 'height', 'params', 'prior_focal_length']
(1, 0, 2736, 3648, b'\x00\x00\x00\x00\x00\xd0\xb1@\x00\x00\x00\x00\x00`\x95@\x00\x00\x00\x00\x00\x80\x9c@', 1)
```

also:

```
(nero) mona@ard-gpu-01:~/NeRO/data/custom/kettle$ sqlite3
SQLite version 3.37.2 2022-01-06 13:25:41
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open database.db
sqlite> .tables
cameras              images               matches            
descriptors          keypoints            two_view_geometries
sqlite> SELECT * FROM cameras;
1|0|2736|3648||1
sqlite> SELECT * FROM descriptors;
1|9244|128|?R   I&
2|9853|128|	(
3|9065|128|q2	
�G
4|9721|128|[
|9838|128|


6|8833|128|'	$j
7|8900|128|
8|8556|128|
9|9721|128|:9	
7)o�w7
10|9357|128|
11|8786|128|"i	
                iJ%� /%iN
12|8211|128|lO'S[
                        B+
	J(
13|8731|128|$
14|8971|128|
15|9261|128|
16|9538|128| kk=
17|9753|128|�)'
               N
        I?
O8|9726|128|#
 &9�)
	
19|10700|128|
20|9589|128|He"
21|8930|128|	
&L
22|8613|128|<F0$
23|9329|128|
24|9830|128|$xG$
Ix'
25|8941|128|
26|8731|128|
27|9326|128|		
/ 	%�#

[Pc
   +(_),�D		8S)
                           +s&!
28|8527|128|
29|9357|128|M&
30|10379|128|
fu
31|10204|128|B
32|9961|128|
33|10756|128|M!
34|8350|128|FE
35|8470|128|9
             %M
-!	?Z%( :
A6r�
 :9i(rr92
36|10041|128|
37|8437|128|~Y
38|8253|128|
Y

39|10895|128|43>� %(G�6
40|10007|128|%	?
(K
41|10177|128|4"+]
42|10746|128|5
43|11171|128|
44|9719|128|�0
45|10218|128|Rw_
46|10370|128|ne2
47|10116|128|�3
2pa9822|128|
49|11344|128|
#&	
50|8636|128|

1|10289|128|
52|8614|128|
            '-
              s�
]5|8938|128|
54|8930|128|

55|8473|128|E$LDoX+#
#oo>!!SfS!6     @NkK
                    oon=
56|8991|128|
57|9602|128|:1
58|9196|128|
59|9873|128|

(8	
        (!
0�
60|8845|128|=

61|9451|128|
62|9902|128|
63|9872|128|
64|9314|128|U�,
65|10296|128|$E$'aE*cg3

[g5	$UG)DN
66|10002|128|.��q/A	nX 
67|9602|128| 
68|9047|128|`
69|8610|128|MqD
70|9851|128|Y)
71|9273|128|R
72|8500|128|G
73|9160|128|\
             �
74|9032|128|t ?	ca)U	Dt<t
75|9838|128|o
76|9762|128|
 7|9772|128|b
Pb4\(
78|8199|128|
M%x%	
79|10508|128|,8J(>
80|8379|128|Q9

81|8847|128|Q 
82|10569|128|?G,
83|9667|128|
           	
"�/             �
84|9180|128|Jb
85|10368|128|JF
PT 9036|128| hE.:&	tqN"
87|8716|128|j!
88|8422|128|!,,

jh
89|9000|128|4
90|9851|128|b
             !S
91|9226|128|.\
92|9213|128|#>)
               \D
93|8792|128|

94|10665|128|M
F^%     *]D   $	
95|9873|128|sP%
96|8585|128|C
97|8474|128|,	
+;
]8|8799|128#C){{]
k%4|9334|128|8oC	|h
135|9546|128|eU
136|8503|128|ls
102|9034|128|QQA
137|8494|128|9
138|9466|128|n=
139|8902|128|'�$	"P( VO
140|8862|128|5E
141|8194|128|'*
142|8973|128|1!P
143|8230|128|	
144|8548|128|T-
145|8785|128|N�
146|9429|128|T)#
147|9077|128|}
148|8508|128|<@
149|8567|128|n2
              nM
150|8241|128|e
151|9381|128|H]
152|9028|128|&
115|8577|128|0n;
153|8746|128|bu
154|9310|128|9X
155|8454|128|  �d
156|8324|128|
157|5879|128|t.
158|8991|128|t8	i`
159|9772|128|k0
@79K-[
sqlite> 
   ![B
      )nO
         .3'*n	
121|9424|128|

122|8822|128|	
                t


"
123|9348|128|A%-$�G
124|10494|128|
125|8949|128|$

AP6|10011|128|
27|9699|128|P$5
�

128|8806|128|T
129|9188|128|sQ
130|8842|128|L	
131|8393|128|?#
132|10565|128|tl
133|9235|128|&FK5


CONTINUES
```

so it seems the database.db is not empty.

**Comment by monajalal** [comment]
There is a problem in your sourcecode. There was no colmap folder inside kettle but the path includes it

```
(nero) mona@ard-gpu-01:~/NeRO$ python run_training.py --cfg configs/custom/kettle_shape.yaml
train set len 99999999
data/custom/kettle/colmap/sparse/0
Provide model format: '.bin' or '.txt'
Traceback (most recent call last):
  File "/home/mona/NeRO/run_training.py", line 10, in <module>
    Trainer(load_cfg(flags.cfg)).run()
  File "/home/mona/NeRO/train/trainer.py", line 100, in run
    self._init_dataset()
  File "/home/mona/NeRO/train/trainer.py", line 45, in _init_dataset
    val_set = name2dataset[val_type](val_cfg, False)
  File "/home/mona/NeRO/dataset/train_dataset.py", line 11, in __init__
    database = parse_database_name(self.cfg['database_name'])
  File "/home/mona/NeRO/dataset/database.py", line 410, in parse_database_name
    return name2database[database_type](database_name)
  File "/home/mona/NeRO/dataset/database.py", line 265, in __init__
    self._parse_colmap()
  File "/home/mona/NeRO/dataset/database.py", line 293, in _parse_colmap
    cameras, images, points3d = read_model(f'{self.root}/colmap/sparse/0')
TypeError: cannot unpack non-iterable NoneType object
```
Here's what I have:
```
(nero) mona@ard-gpu-01:~/NeRO$ ls data/custom/kettle/
total 830M
drwxrwxr-x 2 mona mona 4.0K Jun 10 23:12  images
-rw-r--r-- 1 mona mona 288M Jun 14 10:51  database.db
drwxrwxr-x 3 mona mona 4.0K Jun 14 11:02  sparse
-rw-rw-r-- 1 mona mona 125M Jun 14 19:24  points.ply
-rw-rw-r-- 1 mona mona 140M Jun 14 19:24  points.ply.vis
-rw-rw-r-- 1 mona mona   92 Jun 15 22:47 '`.mlp'
drwxrwxr-x 4 mona mona 4.0K Jun 16 17:13  ..
-rw-r--r-- 1 mona mona 278M Jun 20 12:50  object_point_cloud.ply
-rw-rw-r-- 1 mona mona   60 Jun 20 13:58  meta_info.txt
-rw-rw-r-- 1 mona mona  833 Jun 20 14:27  test_db.py
-rw-r--r-- 1 mona mona    0 Jun 20 14:33  database.db-wal
-rw-r--r-- 1 mona mona  32K Jun 20 14:33  database.db-shm
drwxrwxr-x 5 mona mona 4.0K Jun 20 14:33  .
drwxrwxr-x 5 mona mona 4.0K Jun 20 14:43  dense
```

Realized via this print line
```
        else:
            print(f'{self.root}/colmap/sparse/0')
            cameras, images, points3d = read_model(f'{self.root}/colmap/sparse/0')
```

**Comment by monajalal** [comment]
(nero) mona@ard-gpu-01:~/NeRO$ python run_training.py --cfg configs/custom/kettle_shape.yaml
train set len 99999999
data/custom/kettle/colmap/sparse/0
Detected model format: '.bin'
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 159/159 [00:11<00:00, 14.07it/s]
val val set len 1
